model_params:
  model_name: 'naive'

exp_params:
#  feature_name: 'load' # either in ['solar', 'wind', 'load']
#  prediction_horizon: [60, 1440]
#  location_type: 'single' # 'single' and 'multiple' should be same for naive methods

  test_flag: False
  last_version: 1

  prediction_interval: 0.95

  data_folder: '/home/juan/microgrids/PSML/processed_dataset/forecasting'

trainer_params:

logging_params:
  save_dir: '/home/juan/microgrids/logs'
  name: 'naive'
