name: EnergyForecasting
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.7.15
  - certifi=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=22.3.1
  - pthread-stubs=0.3
  - python=3.7.10
  - readline=8.3
  - setuptools=65.6.3
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.38.4
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==0.15.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==24.2.0
      - cachetools==5.5.2
      - charset-normalizer==3.4.3
      - cycler==0.11.0
      - flatbuffers==1.12
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - future==1.0.0
      - gast==0.3.3
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.32.0
      - h5py==2.10.0
      - idna==3.10
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - joblib==1.3.2
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.4.2
      - multidict==6.0.5
      - numpy==1.19.5
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==1.2.4
      - patsy==1.0.1
      - pillow==9.5.0
      - protobuf==3.20.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydeprecate==0.3.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.3.1
      - pytz==2025.2
      - pyyaml==5.4.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==0.24.2
      - scipy==1.7.3
      - six==1.15.0
      - statsmodels==0.13.5
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.4.1
      - tensorflow-estimator==2.4.0
      - termcolor==1.1.0
      - test-tube==0.7.5
      - threadpoolctl==3.1.0
      - torch==1.8.1+cpu
      - torchdiffeq==0.2.2
      - torchmetrics==0.6.0
      - tqdm==4.67.1
      - typing-extensions==3.7.4.3
      - urllib3==2.0.7
      - werkzeug==2.2.3
      - wrapt==1.12.1
      - yarl==1.9.4
      - zipp==3.15.0